apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
          app: tomcat
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 31122
      port: 80
      targetPort: 8080
